language: node_js
node_js:
- v8
install:
- npm install
- npm install -g lerna yarn
script:
- cd packages/pdf-base && npm run build
- cd packages/ssc-api && npm run build
- cd packages/ssc-pfd && npm run build
- lerna run lint
- lerna bootstrap
cache:
- node_modules
sudo: false